micronaut:
  application:
    name: micronautCamunda
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        enabled: true
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
        enabled: true

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:5432/mn_camunda
    username: mncamunda
    password: mncamunda
    minimum-idle: 10
    maximum-pool-size: 50

camunda:
  admin-user:
    id: admin
    password: admin
  webapps:
    enabled: true
  rest:
    enabled: true
  generic-properties:
    properties:
      initialize-telemetry: true
  filter:
    create: All tasks